spring:
  application:
    name: gateway-server
  config:
    import: "optional:configserver:http://localhost:8079"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  sleuth:
    sampler:
      percentage: 1
  zipkin:
    base-url: http://localhost:9411
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:7080/realms/master/protocol/openid-connect/certs

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
  instance:
    preferIpAddress: true

server:
  port: 8000

logging:
  level:
    com.example.gatewayserver: DEBUG

# Enable refresh config changes
management:
  endpoints:
    web:
      exposure:
        include: "*"

