# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: gatewayserver-deployment
deploymentLabel: gatewayserver

replicaCount: 1

image:
  repository: dactien020796/gateway-server-service
  tag: latest

containerPort: 8000

service:
  type: LoadBalancer
  port: 8000
  targetPort: 8000

config_enabled: true
zipkin_enabled: true
profile_enabled: true
eureka_enabled: true
keycloak_enabled: true