services:
  config-server:
    image: dactien020796/config-server-service
    mem_limit: 700m
    ports:
      - "8079:8079"
    networks:
      - back-tier

  accounts:
    image: dactien020796/accounts-service
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - back-tier

  loans:
    image: dactien020796/loans-service
    mem_limit: 700m
    ports:
      - "8081:8081"
    networks:
      - back-tier

  cards:
    image: dactien020796/cards-service
    mem_limit: 700m
    ports:
      - "8082:8082"
    networks:
      - back-tier

networks:
  back-tier: {}