services:
  accounts:
    image: dactien020796/accounts-service
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - back-tier

  loans:
    image: dactien020796/loans-service
    mem_limit: 700m
    ports:
      - "8081:8080"
    networks:
      - back-tier

  cards:
    image: dactien020796/cards-service
    mem_limit: 700m
    ports:
      - "8082:8080"
    networks:
      - back-tier

networks:
  back-tier: {}