spring:
  application:
    name: account-service
  datasource:
    username: sa
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
#  profiles:
#    active: dev
#  config:
#    import: "optional:configserver:http://localhost:8079"
  sleuth:
    sampler:
      percentage: 1
  zipkin:
    base-url: http://localhost:9411

#eureka:
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    serviceUrl:
#      defaultZone: http://localhost:8070/eureka/
#  instance:
#    preferIpAddress: true

server:
  port: 8080

urls:
  card-service: http://localhost:8081
  loan-service: http://localhost:8082

# Enable refresh config changes
management:
  endpoints:
    web:
      exposure:
        include: "*"

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
    instances:
      getCustomerDetail:
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 30000
        permittedNumberOfCallsInHalfOpenState: 2
