# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: loans-deployment
deploymentLabel: loans

replicaCount: 1

image:
  repository: dactien020796/loans-service
  tag: latest

containerPort: 8081

service:
  type: ClusterIP
  port: 8081
  targetPort: 8081

config_enabled: true
zipkin_enabled: true
profile_enabled: true
eureka_enabled: true
keycloak_enabled: false