deploymentName: accounts-deployment
deploymentLabel: accounts

replicaCount: 1

image:
  repository: dactien020796/accounts-service
  tag: latest

containerPort: 8080

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

config_enabled: true
zipkin_enabled: true
profile_enabled: true
eureka_enabled: true
keycloak_enabled: false