spring:
  application:
    name: eureka-server
  config:
    import: "optional:configserver:http://localhost:8079"
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  sleuth:
    sampler:
      percentage: 1
  zipkin:
    base-url: http://localhost:9411