spring:
  application:
    name: config-server
# Load from classpath/file system
#  profiles:
#    active: native
#  cloud:
#    config:
#      server:
#        native:
#          searchLocations: "classpath:/config"

# Load from Github
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dactien020796/java-spring-docker-kubernetes-config-server.git
          clone-on-start: true
          default-label: main
  sleuth:
    sampler:
      percentage: 1
  zipkin:
    base-url: http://localhost:9411

server:
  port: 8079

encrypt:
  key: sceret_key