# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: cards-deployment
deploymentLabel: cards

replicaCount: 1

image:
  repository: dactien020796/cards-service
  tag: latest

containerPort: 8082

service:
  type: ClusterIP
  port: 8082
  targetPort: 8082

config_enabled: true
zipkin_enabled: true
profile_enabled: true
eureka_enabled: true